AWSTemplateFormatVersion: 2010-09-09
Resources:
  IAMTest:
    Type: Richard::Cloud9::Environment
    Properties:
      InstanceType: c5.large
      EBSVolumeSize: 50
      OwnerArn: "arn:aws:sts::908752905784:assumed-role/CrossAccountRole-RootRole-1AYURKOCV4R8Y/rhboyd-Isengard"
      SSHKeyLocation: "arn:aws:secretsmanager:us-west-2:908752905784:secret:dev/github/richardhboyd-A0wBeT"
      UserData: 
        Fn::Base64: |
          cd /
          VERSION=3.7.4
          yum update -y
          yum install gcc openssl-devel bzip2-devel libffi-devel -y
          wget https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz
          tar xzf Python-${VERSION}.tgz
          cd Python-${VERSION}
          echo "Building Python"
          ./configure --enable-optimizations
          echo "Installing Python"
          make altinstall
          cd ../
          # Remove old symlinks
          rm -rf /etc/alternatives/pip
          rm -rf /etc/alternatives/python
          # make new symlinks
          ln -s /usr/local/bin/pip${VERSION:0:3} /etc/alternatives/pip
          ln -s /usr/local/bin/python${VERSION:0:3} /etc/alternatives/python
          ## Java
          wget https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm
          yum localinstall amazon-corretto*.rpm
          ## User Local stuff (brew HATES to be run by root)
          cd /home/ec2-user/
          echo "Creating user-script"
          cat <<'EOF' > ./script.sh
          export HOME=/home/ec2-user/
          CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
          test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
          echo "eval \$($(/home/linuxbrew/.linuxbrew/bin/brew --prefix)/bin/brew shellenv)" >>~/.profile
          npm uninstall -g aws-sam-local
          sudo pip uninstall aws-sam-cli
          sudo rm -rf $(which sam)
          brew tap aws/tap
          brew install aws-sam-cli
          ln -sf $(which sam) ~/.c9/bin/sam
          npm uninstall -g typescript
          npm install -g typescript
          tsc --version
          git config --global user.name "Richard Boyd"
          git config --global user.email rhboyd@amazon.com
          EOF
          echo "Running user-script"
          chmod +x ./script.sh
          runuser -l  ec2-user -c './script.sh'
          echo "done" >> /home/ec2-user/environment/DONE.txt